version: '3.0'

services:
  contoso-web:
    image: vslaunch-contoso-web-v2
    ports:
            - "8080:80"
            - "8443:443"
    build:
      context: .
      dockerfile: Contoso.Web/Dockerfile
    depends_on:
            - contoso-db
            - contoso-api
    
  contoso-api:
    image: vslaunch-contoso-api-v2
    ports:
            - "8081:80"
            - "8444:443"
    build:
      context: .
      dockerfile: Contoso.Api/Dockerfile
    depends_on:
            - contoso-db
    
  contoso-db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Developer@123#"
            ACCEPT_EULA: "Y"