version: '3.0'

services:
  contoso-web:
          build:
            context: .
            dockerfile: Contoso.Web/Dockerfile

          image: vslaunch/contoso-web
          ports:
                  - "8080:80"
                  - "8443:443"
   
          depends_on:
                  - contoso-db
                  - contoso-api
  
  contoso-api:
          build:
            context: .
            dockerfile: Contoso.Api/Dockerfile

          image: vslaunch/contoso-api
          ports:
                  - "8081:80"
                  - "8444:443"
    
          depends_on:
                  - contoso-db
  contoso-db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Developer@123#"
            ACCEPT_EULA: "Y"